# Generated by Django 4.1.4 on 2022-12-12 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(choices=[('mysql', 'mysql'), ('mongodb', 'mongodb'), ('redis', 'redis')], default='mysql', max_length=10, verbose_name='所属数据库类型')),
                ('address', models.CharField(default='127.0.0.1', max_length=50, verbose_name='链接地址：IP:Port')),
                ('username', models.CharField(blank=True, default='admin', max_length=10, verbose_name='用户')),
                ('password', models.CharField(blank=True, default='admin', max_length=200, verbose_name='密码')),
                ('uri', models.CharField(default='mongo://127.0.0.1:27017', max_length=200, verbose_name='uri连接地址')),
                ('desc', models.TextField(verbose_name='备注')),
            ],
            options={
                'db_table': 't_db',
            },
        ),
        migrations.CreateModel(
            name='KubernetesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=32, verbose_name='集群名称')),
                ('address', models.CharField(default='default', max_length=32, verbose_name='地址')),
                ('token', models.TextField(blank=True, verbose_name='认证token')),
                ('desc', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'db_table': 't_kubernetes',
            },
        ),
        migrations.CreateModel(
            name='KubernetesWorkLoadServiceIngressTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(default='default', max_length=32, verbose_name='名称')),
                ('class_type', models.CharField(default='default', max_length=32, verbose_name='类型')),
                ('template', models.TextField(verbose_name='模板内容')),
                ('desc', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'db_table': 't_kubernetes_template',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('finish_time', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_time', models.CharField(default='default', max_length=32, verbose_name='类型名称')),
                ('kubernetes_content', models.TextField(verbose_name='kubernetes内容')),
                ('db_content', models.TextField(verbose_name='模板内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0, verbose_name='任务状态')),
                ('desc', models.TextField(blank=True, verbose_name='备注')),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.db', verbose_name='所属db')),
                ('kubernetes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.kubernetesmodel', verbose_name='所属Kubernetes')),
            ],
            options={
                'db_table': 't_orders',
            },
        ),
        migrations.CreateModel(
            name='KubernetesNameSpace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=32, verbose_name='集群名称')),
                ('namespace', models.CharField(default='default', max_length=32, verbose_name='命名空间')),
                ('desc', models.TextField(blank=True, verbose_name='备注')),
                ('kubernetes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.kubernetesmodel', verbose_name='所属Kubernetes')),
            ],
            options={
                'db_table': 't_kubernetes_namespace',
            },
        ),
    ]
