# Generated by Django 4.1.4 on 2022-12-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kubernetesmodel',
            name='regular',
            field=models.TextField(null=True, verbose_name='正则信息'),
        ),
    ]
