# Generated by Django 4.1.4 on 2022-12-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_kubernetesmodel_regular'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.CharField(choices=[('wechat', '企业微信'), ('dingtalk', '钉钉'), ('email', '邮件')], default='weichat', max_length=10, verbose_name='通知类型')),
                ('params', models.TextField(verbose_name='通知参数')),
            ],
        ),
        migrations.AlterField(
            model_name='kubernetesnamespace',
            name='name',
            field=models.CharField(default='default', max_length=32, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='orders',
            name='notice',
            field=models.ManyToManyField(to='order.ordernotice', verbose_name='通知类型'),
        ),
    ]
