# Generated by Django 4.1.4 on 2022-12-22 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_ordernotice_alter_kubernetesnamespace_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernotice',
            name='at_useful',
            field=models.BooleanField(default=False, verbose_name='at_useful'),
        ),
        migrations.AddField(
            model_name='orders',
            name='old_orders',
            field=models.ManyToManyField(to='order.orders', verbose_name='回退工单'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.db', verbose_name='所属db'),
        ),
    ]
