# Generated by Django 4.1.4 on 2023-01-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_ordernotice_at_useful_orders_old_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kubernetesmodel',
            name='ca',
            field=models.TextField(null=True, verbose_name='证书'),
        ),
        migrations.AddField(
            model_name='kubernetesmodel',
            name='debug',
            field=models.BooleanField(default=False, verbose_name='debug'),
        ),
    ]
