# Generated by Django 4.1.4 on 2022-12-12 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('name', models.CharField(default='default', max_length=50, verbose_name='姓名')),
                ('mobile', models.CharField(default='186000000000', max_length=12, verbose_name='手机')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='有效')),
                ('is_staff', models.BooleanField(default=True, verbose_name='员工')),
                ('is_superuser', models.BooleanField(default=True, verbose_name='是否是超级用户')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建日期')),
                ('update_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='更新日期')),
                ('last_login', models.DateTimeField(auto_now_add=True, null=True, verbose_name='最近登录')),
                ('account_type', models.CharField(choices=[('创建', 'create'), ('ad', 'ad域控'), ('ldap', 'LDAP')], default='create', max_length=20, verbose_name='账号类型')),
            ],
            options={
                'verbose_name_plural': 'User',
                'db_table': 'sys_users',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=32, verbose_name='权限')),
                ('path', models.CharField(default='default', max_length=32, verbose_name='权限目录')),
                ('desc', models.TextField(blank=True, verbose_name='权限描述')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=32, verbose_name='角色')),
                ('desc', models.TextField(blank=True, verbose_name='角色描述')),
            ],
            options={
                'db_table': 'sys_roles',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, max_length=60)),
                ('update_date', models.DateTimeField(default=0, verbose_name='更新日期')),
                ('expiration_time', models.DateTimeField(default=0, verbose_name='失效时间')),
                ('username', models.OneToOneField(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户token表',
                'verbose_name_plural': '用户token表',
                'db_table': 'sys_token',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='account.role', verbose_name='角色'),
        ),
    ]
