# Generated by Django 4.1.4 on 2022-12-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_usertoken_token_alter_usertoken_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalLdapConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldap_server', models.CharField(default='127.0.0.1:389', max_length=30, verbose_name='地址')),
                ('ldap_binddn', models.CharField(default='default', max_length=80, verbose_name='监听账号')),
                ('ldap_bindpass', models.CharField(default='default', max_length=80, verbose_name='监听密码')),
                ('ldap_login_attribute', models.CharField(default='', max_length=50, verbose_name='登录关键字')),
                ('ldap_base_dn', models.CharField(default='ou', max_length=50, verbose_name='登录搜索域')),
                ('desc', models.TextField(verbose_name='备注')),
            ],
            options={
                'db_table': 'sys_ldap',
            },
        ),
    ]
